# Generated by Django 5.2.6 on 2025-09-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=150)),
                ('published', models.DateTimeField()),
                ('sentiment_label', models.CharField(max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_model', models.CharField(blank=True, null=True)),
                ('sentiment_lang', models.CharField(blank=True, null=True)),
                ('sentiment_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketCandle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('open', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketdata', to='core.company', unique=True)),
            ],
        ),
    ]
