# Generated by Django 5.2.6 on 2025-09-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment_lang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment_model',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketdata', to='core.company'),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['company', '-published'], name='articles_company_ecc85e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published'], name='articles_publish_213ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcandle',
            index=models.Index(fields=['company', 'ts'], name='market_cand_company_40c5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcandle',
            index=models.Index(fields=['-ts'], name='market_cand_ts_8d53cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketcandle',
            constraint=models.UniqueConstraint(fields=('company', 'ts'), name='unique_candle_company_ts'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='marketcandle',
            table='market_candle',
        ),
    ]
